name: Bug Report
description: File a bug report
body:
  - type: dropdown
    id: version
    attributes:
      label: Component
      description: What component/project does this related to?
      options:
        - Infrastructure
        - Platform
        - ODE
        - Other
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Specifics
      description: Select any related subcomponent(s)
      options:
        - label: CircleCI
        - label: Docker or Docker Hub
        - label: Doxygen
        - label: GitHub Actions
        - label: GitHub branch or repo
        - label: Sonar
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
