name: Bug Report
description: File a bug report
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Component
      description: What component/project does this related to?
      options:
        - Infrastructure
        - CI/CD
        - Other
    validations:
      required: true