name: Scheduled GitHub Repo Settings Scan

on:
  push:
    branches:
      - fix-github-settings-audit
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 8 * * 1-5"
    - cron: "0 9 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      actions: read
      checks: read
      contents: read
      deployments: read
      packages: read
      pull-requests: read
      repository-projects: read
      security-events: read
      statuses: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install -r audit-github-repo-settings_requirements.txt
      - name: Test github token
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api /repos/usdot-fhwa-stol/devops/branches/develop/protection

      - name: Scan develop branches
        env:
          DEVOPS_GITHUB_TOKEN: ${{ secrets.DEVOPS_GITHUB_TOKEN }}
        run: |
          ./audit-github-repo-settings.py \
            --branches develop \
            --github-token $DEVOPS_GITHUB_TOKEN \
            --open-github-issues \
            --organizations usdot-fhwa-stol usdot-jpo-ode

      - name: Scan master branches
        env:
          DEVOPS_GITHUB_TOKEN: ${{ secrets.DEVOPS_GITHUB_TOKEN }}  
        run: |
          ./audit-github-repo-settings.py \
            --branches master \
            --github-token $DEVOPS_GITHUB_TOKEN  \
            --open-github-issues \
            --organizations usdot-fhwa-stol usdot-jpo-ode

      - name: Scan main branches
        env:
          DEVOPS_GITHUB_TOKEN: ${{ secrets.DEVOPS_GITHUB_TOKEN }}
        run: |
          ./audit-github-repo-settings.py \
            --branches main \
            --github-token $DEVOPS_GITHUB_TOKEN \
            --open-github-issues \
            --organizations usdot-fhwa-stol usdot-jpo-ode
