name: Scheduled GitHub Repo Settings Scan

on:
  push:
    branches:
      - fix-github-settings-audit
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 8 * * 1-5"
    - cron: "0 9 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install -r audit-github-repo-settings_requirements.txt

      - name: Scan develop branches
        run: |
          ./audit-github-repo-settings.py \
            --branches develop \
            --github-token ${{ secrets.GITHUB_TOKEN }} \
            --open-github-issues \
            --organizations usdot-fhwa-stol usdot-jpo-ode

      - name: Scan master branches  
        run: |
          ./audit-github-repo-settings.py \
            --branches master \
            --github-token ${{ secrets.GITHUB_TOKEN }} \
            --open-github-issues \
            --organizations usdot-fhwa-stol usdot-jpo-ode

      - name: Scan main branches
        run: |
          ./audit-github-repo-settings.py \
            --branches main \
            --github-token "${{ secrets.GITHUB_TOKEN }}" \
            --open-github-issues \
            --organizations usdot-fhwa-stol usdot-jpo-ode
